spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"

jwt:
  private-key: keys/private_key.pem

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/device_registry
    username: services
    password: password

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:postgresql://PostgreSQL:5432/device_registry
    username: services
    password: password

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
