jwt:
  private-key: cert/valid-private-key.pem

spring:
  r2dbc:
    url: r2dbc:postgresql://placeholder
    username: placeholder
    password: placeholder

container:
  postgres:
    version: postgres:17
    init: postgres/schema.sql
    before: postgres/data.sql
    after: postgres/reset.sql
